"""
Generate PDF Stock Analysis Report V2
- Menggunakan data yang SAMA dengan localhost
- Periode: 5 hari (short-term) + 12 hari (optimal)
- Output: STOCKCODE_YYYYMMDD.pdf
"""
import sys
import os
import json
from datetime import datetime
from fpdf import FPDF

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from database import execute_query
from analyzer import calculate_optimal_lookback_days
from signal_validation import get_comprehensive_validation
from composite_analyzer import (
    get_comprehensive_analysis,
    calculate_price_movements,
    analyze_support_resistance
)
from broker_config import is_foreign_broker

# Periode optimal berdasarkan perhitungan sistem
SHORT_TERM_DAYS = 5   # 1 minggu trading
OPTIMAL_DAYS = 12     # Optimal dari pola historis

class StockReportPDF(FPDF):
    def __init__(self, stock_code):
        super().__init__()
        self.stock_code = stock_code
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Analisis Saham {self.stock_code} - HermanStock', align='L')
        self.cell(0, 10, datetime.now().strftime('%d %B %Y'), align='R', new_x='LMARGIN', new_y='NEXT')
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Halaman {self.page_no()}/{{nb}} | Generated by Claude AI', align='C')

    def chapter_title(self, num, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_fill_color(41, 128, 185)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, f'  {num}. {title}', fill=True, new_x='LMARGIN', new_y='NEXT')
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(41, 128, 185)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def key_value(self, key, value, color=None):
        self.set_font('Helvetica', 'B', 10)
        self.cell(70, 6, key + ":")
        self.set_font('Helvetica', '', 10)
        if color:
            self.set_text_color(*color)
        self.cell(0, 6, str(value), new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)

    def add_table(self, headers, data, col_widths=None):
        if col_widths is None:
            col_widths = [190 / len(headers)] * len(headers)
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(230, 230, 230)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, border=1, fill=True, align='C')
        self.ln()
        self.set_font('Helvetica', '', 9)
        for row in data:
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 6, str(cell)[:25], border=1, align='C')
            self.ln()
        self.ln(3)


def get_stock_profile(stock_code):
    result = execute_query("SELECT * FROM stock_profile WHERE stock_code = %s", (stock_code,))
    return dict(result[0]) if result else {}

def get_stock_fundamental(stock_code):
    result = execute_query("""
        SELECT * FROM stock_fundamental WHERE stock_code = %s
        ORDER BY report_date DESC LIMIT 1
    """, (stock_code,))
    if result:
        d = dict(result[0])
        for k, v in d.items():
            if hasattr(v, '__float__'):
                d[k] = float(v)
        return d
    return {}

def get_daily_prices(stock_code, days):
    """Get daily price data for N trading days"""
    result = execute_query("""
        SELECT date, open_price, high_price, low_price, close_price, volume, value
        FROM stock_daily WHERE stock_code = %s
        ORDER BY date DESC LIMIT %s
    """, (stock_code, days))
    return [dict(r) for r in result] if result else []

def get_broker_flow(stock_code, days):
    """Get broker flow for N trading days with foreign/local breakdown"""
    result = execute_query("""
        WITH last_n_days AS (
            SELECT DISTINCT date FROM stock_daily
            WHERE stock_code = %s ORDER BY date DESC LIMIT %s
        )
        SELECT
            broker_code,
            SUM(buy_value) as total_buy,
            SUM(sell_value) as total_sell,
            SUM(net_value) as net_value,
            SUM(net_lot) as net_lot,
            COUNT(*) as active_days
        FROM broker_summary
        WHERE stock_code = %s AND date IN (SELECT date FROM last_n_days)
        GROUP BY broker_code
        ORDER BY net_value DESC
    """, (stock_code, days, stock_code))

    buyers = []
    sellers = []
    foreign_net = 0
    local_net = 0
    foreign_buyers = []
    local_buyers = []
    foreign_sellers = []
    local_sellers = []

    for r in result:
        broker = r['broker_code']
        net = float(r['net_value'] or 0)
        row = {
            'broker': broker,
            'net_value': net,
            'net_lot': float(r['net_lot'] or 0),
            'active_days': r['active_days'],
            'is_foreign': is_foreign_broker(broker)
        }

        # Overall
        if net > 0:
            buyers.append(row)
        elif net < 0:
            sellers.append(row)

        # Foreign vs Local breakdown
        if is_foreign_broker(broker):
            foreign_net += net
            if net > 0:
                foreign_buyers.append(row)
            elif net < 0:
                foreign_sellers.append(row)
        else:
            local_net += net
            if net > 0:
                local_buyers.append(row)
            elif net < 0:
                local_sellers.append(row)

    return {
        'top_buyers': buyers[:5],
        'top_sellers': sorted(sellers, key=lambda x: x['net_value'])[:5],
        'total_net': sum(float(r['net_value'] or 0) for r in result),
        # Foreign breakdown
        'foreign_net': foreign_net,
        'foreign_buyers': sorted(foreign_buyers, key=lambda x: -x['net_value'])[:5],
        'foreign_sellers': sorted(foreign_sellers, key=lambda x: x['net_value'])[:5],
        # Local breakdown
        'local_net': local_net,
        'local_buyers': sorted(local_buyers, key=lambda x: -x['net_value'])[:5],
        'local_sellers': sorted(local_sellers, key=lambda x: x['net_value'])[:5]
    }

def get_accumulation_signal_from_validation(stock_code):
    """Get accumulation signal SAMA PERSIS dengan localhost Analysis page"""
    validation = get_comprehensive_validation(stock_code)
    detection = validation.get('detection', {})
    validations = validation.get('validations', {})

    current_signal = detection.get('current_signal', 'NEUTRAL')

    # Map signal to display
    signal_map = {
        'ACCUMULATION': 'AKUMULASI',
        'DISTRIBUTION': 'DISTRIBUSI',
        'NEUTRAL': 'NETRAL',
        'STRONG_ACCUMULATION': 'AKUMULASI KUAT',
        'STRONG_DISTRIBUTION': 'DISTRIBUSI KUAT'
    }

    signal = signal_map.get(current_signal, 'NETRAL')

    # Color
    if 'AKUMULASI' in signal:
        color = (0, 150, 0)
    elif 'DISTRIBUSI' in signal:
        color = (200, 0, 0)
    else:
        color = (150, 150, 0)

    # Get CPR
    cpr_data = validations.get('cpr', {})
    cpr_pct = cpr_data.get('cpr_pct', 0)
    cpr_signal = cpr_data.get('signal', 'N/A')

    # Get component signals
    components = {}
    for key, val in validations.items():
        if isinstance(val, dict) and 'signal' in val:
            components[key] = val.get('signal', 'N/A')

    return {
        'signal': signal,
        'color': color,
        'cpr_pct': cpr_pct,
        'cpr_signal': cpr_signal,
        'components': components,
        'strength': detection.get('current_strength')
    }


def get_broker_flow_stats(stock_code, days):
    """Get broker flow statistics for N trading days"""
    result = execute_query("""
        WITH last_n_days AS (
            SELECT DISTINCT date FROM stock_daily
            WHERE stock_code = %s ORDER BY date DESC LIMIT %s
        ),
        daily_stats AS (
            SELECT
                bs.date,
                SUM(CASE WHEN bs.net_value > 0 THEN 1 ELSE 0 END) as num_buyers,
                SUM(CASE WHEN bs.net_value < 0 THEN 1 ELSE 0 END) as num_sellers,
                SUM(bs.net_value) as daily_net
            FROM broker_summary bs
            WHERE bs.stock_code = %s AND bs.date IN (SELECT date FROM last_n_days)
            GROUP BY bs.date
        )
        SELECT
            COUNT(*) as total_days,
            SUM(CASE WHEN num_buyers > num_sellers THEN 1 ELSE 0 END) as accum_days,
            SUM(CASE WHEN num_sellers > num_buyers THEN 1 ELSE 0 END) as dist_days,
            SUM(daily_net) as total_net
        FROM daily_stats
    """, (stock_code, days, stock_code))

    if not result:
        return {'accum_days': 0, 'dist_days': 0, 'total_days': 0, 'total_net': 0}

    r = result[0]
    return {
        'accum_days': r['accum_days'] or 0,
        'dist_days': r['dist_days'] or 0,
        'total_days': r['total_days'] or 0,
        'total_net': float(r['total_net'] or 0)
    }

def format_rupiah(val):
    if val is None:
        return "N/A"
    if abs(val) >= 1e12:
        return f"Rp {val/1e12:.2f} T"
    elif abs(val) >= 1e9:
        return f"Rp {val/1e9:.2f} M"
    elif abs(val) >= 1e6:
        return f"Rp {val/1e6:.2f} Jt"
    else:
        return f"Rp {val:,.0f}"


def generate_signal_education(validation_data, accum_signal, broker_data, fundamental):
    """
    Generate dynamic educational explanation based on actual data.
    Bukan template - analisis berdasarkan kondisi real.
    """
    detection = validation_data.get('detection', {})
    validations = validation_data.get('validations', {})
    decision_rule = validation_data.get('decision_rule', {})

    signal = accum_signal['signal']
    decision = decision_rule.get('decision', 'WAIT')
    components = accum_signal.get('components', {})
    cpr_pct = accum_signal.get('cpr_pct', 50)

    education = {
        'signal_explanation': '',
        'why_not_buy': [],
        'wait_for_confirmation': [],
        'positive_factors': [],
        'warning_factors': []
    }

    # ══════════════════════════════════════════════════════════════
    # ANALISIS KONDISI AKTUAL (bukan template)
    # ══════════════════════════════════════════════════════════════

    # 1. Analisis CPR
    if cpr_pct < 30:
        education['why_not_buy'].append(f"CPR hanya {cpr_pct}% - harga ditutup dekat LOW, seller masih dominan")
        education['wait_for_confirmation'].append("CPR naik ke >50% (close mendekati HIGH)")
    elif cpr_pct > 70:
        education['positive_factors'].append(f"CPR {cpr_pct}% - buyer berhasil push harga ke atas")

    # 2. Analisis UVDV (Up Volume vs Down Volume)
    uvdv_signal = components.get('uvdv', '')
    if 'DISTRIBUSI' in str(uvdv_signal).upper():
        education['why_not_buy'].append("Volume saat harga turun lebih besar dari volume saat harga naik")
        education['wait_for_confirmation'].append("Volume buying > volume selling konsisten 3+ hari")
    elif 'AKUMULASI' in str(uvdv_signal).upper():
        education['positive_factors'].append("Volume buying mendominasi - institusi aktif mengumpulkan")

    # 3. Analisis Broker Influence
    broker_sig = components.get('broker_influence', '')
    if 'AKUMULASI' in str(broker_sig).upper():
        education['positive_factors'].append("Broker besar sedang akumulasi - smart money masuk")
    elif 'DISTRIBUSI' in str(broker_sig).upper():
        education['why_not_buy'].append("Broker besar sedang jual - smart money keluar")
        education['wait_for_confirmation'].append("Broker institusi berbalik arah dari sell ke buy")

    # 4. Analisis Persistence
    persist_sig = components.get('persistence', '')
    if persist_sig and 'N/A' not in str(persist_sig):
        if 'AKUMULASI' in str(persist_sig).upper():
            education['positive_factors'].append("Pola akumulasi sudah berlangsung konsisten (persistence)")

    # 5. Analisis Failed Breaks
    failed_sig = components.get('failed_breaks', '')
    if 'AKUMULASI' in str(failed_sig).upper():
        education['positive_factors'].append("Ada buying saat breakdown gagal - support kuat")

    # 6. Analisis Elasticity
    elastic_sig = components.get('elasticity', '')
    if 'PENAHAN' in str(elastic_sig).upper():
        education['positive_factors'].append("Ada penahan di bawah - support aktif")
    elif 'DISTRIBUSI' in str(elastic_sig).upper():
        education['why_not_buy'].append("Harga mudah turun tapi sulit naik - supply masih besar")
        education['wait_for_confirmation'].append("Harga mampu bertahan di atas resistance sebelumnya")

    # 7. Analisis Rotation
    rotation_sig = components.get('rotation', '')
    if 'SEHAT' in str(rotation_sig).upper():
        education['positive_factors'].append("Rotasi broker sehat - bukan pump and dump")
    elif 'GORENG' in str(rotation_sig).upper():
        education['warning_factors'].append("Hati-hati: Pola rotasi tidak sehat, potensi saham gorengan")

    # 8. Analisis Resistance
    resistance_data = validations.get('failed_breaks', {})
    if resistance_data.get('active_resistance'):
        education['why_not_buy'].append("Resistance aktif di atas - seller defend di level tersebut")
        education['wait_for_confirmation'].append("Breakout menembus resistance dengan volume tinggi")

    # 9. Analisis Foreign Flow
    foreign_net = broker_data.get('foreign_net', 0)
    if foreign_net < 0:
        education['warning_factors'].append(f"Asing net sell {format_rupiah(abs(foreign_net))} - foreign outflow")
    elif foreign_net > 0:
        education['positive_factors'].append(f"Asing net buy {format_rupiah(foreign_net)} - foreign inflow")

    # 10. Analisis Fundamental
    per = fundamental.get('per', 0)
    pbv = fundamental.get('pbvr', 0)
    if per > 50:
        education['warning_factors'].append(f"PER {per:.1f}x sangat tinggi - valuasi stretched")
    if pbv > 5:
        education['warning_factors'].append(f"PBV {pbv:.1f}x tinggi - premium terhadap book value")

    # ══════════════════════════════════════════════════════════════
    # GENERATE MAIN EXPLANATION
    # ══════════════════════════════════════════════════════════════

    if signal == 'NETRAL' or decision == 'WAIT':
        # Mixed signal - perlu penjelasan detail
        if education['why_not_buy'] and education['positive_factors']:
            education['signal_explanation'] = (
                f"Status {signal}: Meskipun ada beberapa sinyal positif "
                f"({len(education['positive_factors'])} faktor), "
                f"masih ada {len(education['why_not_buy'])} kondisi yang belum mendukung. "
                f"Sistem menunggu konfirmasi sebelum memberikan sinyal entry untuk melindungi dari false signal."
            )
        elif education['why_not_buy']:
            education['signal_explanation'] = (
                f"Status {signal}: Terdeteksi {len(education['why_not_buy'])} kondisi negatif. "
                f"Sistem menyarankan WAIT sampai kondisi membaik untuk menghindari entry prematur."
            )
        else:
            education['signal_explanation'] = (
                f"Status {signal}: Belum ada sinyal dominan yang jelas. "
                f"Kondisi market sideways atau dalam transisi. Tunggu breakout atau breakdown untuk arah yang lebih jelas."
            )

    elif 'AKUMULASI' in signal:
        education['signal_explanation'] = (
            f"Status {signal}: {len(education['positive_factors'])} faktor positif terdeteksi. "
            f"Institusi sedang mengumpulkan saham. "
            f"Namun tetap perhatikan {len(education['warning_factors'])} faktor risiko jika ada."
        )

    elif 'DISTRIBUSI' in signal:
        education['signal_explanation'] = (
            f"Status {signal}: Terdeteksi {len(education['why_not_buy'])} sinyal distribusi. "
            f"Institusi sedang menjual/mengurangi posisi. "
            f"Tidak disarankan entry sampai pola distribusi berakhir."
        )

    return education


def generate_absorption_explanation(cpr_pct, broker_data, decision):
    """
    Special explanation untuk status ABSORPTION (WAIT dengan net buy positif tapi CPR rendah)
    """
    if decision != 'WAIT':
        return None

    total_net = broker_data.get('total_net', 0)
    if total_net <= 0:
        return None

    # Ada net buy tapi signal WAIT - ini ABSORPTION
    if cpr_pct < 40:
        return {
            'title': 'Kenapa WAIT padahal ada Net Buy?',
            'explanation': (
                f"Meskipun broker mencatat net buy {format_rupiah(total_net)}, "
                f"harga masih ditutup di area bawah (CPR {cpr_pct}%). "
                f"Ini menandakan supply masih aktif menyerap buying pressure. "
                f"Istilahnya: ABSORPTION - buyer sudah masuk tapi belum mampu push harga. "
                f"Sistem menunggu konfirmasi buyer berhasil mengangkat harga (CPR >50%) sebelum entry."
            ),
            'what_to_wait': [
                "Close di atas middle range (CPR >50%)",
                "Volume buying konsisten meningkat",
                "Resistance terdekat berhasil ditembus"
            ]
        }
    return None


def generate_pdf_report(stock_code, output_dir=None):
    """Generate PDF dengan 2 analisa: 5 hari + 12 hari"""

    if output_dir is None:
        output_dir = r"C:\doc Herman\analisa analysis"
    os.makedirs(output_dir, exist_ok=True)

    print(f"Mengambil data {stock_code}...")

    # Get basic data
    profile = get_stock_profile(stock_code)
    fundamental = get_stock_fundamental(stock_code)

    # Get validation data (SAMA dengan localhost Analysis page)
    validation = get_comprehensive_validation(stock_code)
    decision = validation.get('decision_rule', {})
    detection = validation.get('detection', {})

    # Get price data
    prices_5d = get_daily_prices(stock_code, SHORT_TERM_DAYS)
    prices_12d = get_daily_prices(stock_code, OPTIMAL_DAYS)
    current_price = float(prices_5d[0]['close_price']) if prices_5d else 0

    # Get broker flow untuk 2 periode
    broker_5d = get_broker_flow(stock_code, SHORT_TERM_DAYS)
    broker_12d = get_broker_flow(stock_code, OPTIMAL_DAYS)

    # Get accumulation signal dari validation (SAMA dengan localhost)
    accum_main = get_accumulation_signal_from_validation(stock_code)

    # Get broker flow stats untuk 2 periode
    flow_stats_5d = get_broker_flow_stats(stock_code, SHORT_TERM_DAYS)
    flow_stats_12d = get_broker_flow_stats(stock_code, OPTIMAL_DAYS)

    # Get support/resistance
    sr = analyze_support_resistance(stock_code)
    supports = sr.get('supports', [])
    resistances = sr.get('resistances', [])

    # ════════════════════════════════════════════════════════════
    # CREATE PDF
    # ════════════════════════════════════════════════════════════
    pdf = StockReportPDF(stock_code)
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 15, f'ANALISIS SAHAM {stock_code}', align='C', new_x='LMARGIN', new_y='NEXT')

    company_name = profile.get('company_name', stock_code)
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, company_name, align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(5)

    # Main Signal Box
    main_signal = detection.get('current_signal', 'N/A')
    main_decision = decision.get('decision', 'WAIT')
    position = decision.get('current_vs_entry', 'N/A')

    pdf.set_fill_color(245, 245, 245)
    pdf.rect(10, pdf.get_y(), 190, 30, 'DF')

    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(63, 15, f'Harga: Rp {current_price:,.0f}', align='C')

    # Signal color
    if main_decision == 'BUY':
        pdf.set_text_color(0, 150, 0)
    elif main_decision == 'SELL':
        pdf.set_text_color(200, 0, 0)
    else:
        pdf.set_text_color(200, 150, 0)
    pdf.cell(63, 15, f'{main_decision}', align='C')

    pdf.set_text_color(41, 128, 185)
    pdf.cell(64, 15, f'{position}', align='C', new_x='LMARGIN', new_y='NEXT')

    pdf.set_text_color(100, 100, 100)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.cell(0, 10, decision.get('reason', ''), align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # ════════════════════════════════════════════════════════════
    # ANALISA 1: DATA HARIAN (5 Hari Trading)
    # ════════════════════════════════════════════════════════════
    pdf.chapter_title(1, f"ANALISA SHORT-TERM ({SHORT_TERM_DAYS} Hari Trading)")

    pdf.section_title("A. Pergerakan Harga Harian")
    if prices_5d:
        price_table = []
        for p in prices_5d:
            date_str = str(p['date'])[:10]
            close = float(p['close_price'])
            high = float(p['high_price'])
            low = float(p['low_price'])
            vol = float(p['volume'] or 0)
            price_table.append([
                date_str,
                f"{close:,.0f}",
                f"{high:,.0f}",
                f"{low:,.0f}",
                f"{vol/1e6:.1f}M"
            ])
        pdf.add_table(
            ["Tanggal", "Close", "High", "Low", "Volume"],
            price_table,
            [40, 35, 35, 35, 45]
        )

    pdf.section_title("B. Broker Flow (5 Hari)")
    pdf.key_value("Total Net Flow", format_rupiah(broker_5d['total_net']))

    # Foreign vs Local breakdown
    pdf.ln(2)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(0, 100, 200)
    pdf.cell(95, 6, f"ASING: {format_rupiah(broker_5d['foreign_net'])}")
    pdf.set_text_color(100, 100, 100)
    pdf.cell(95, 6, f"LOKAL: {format_rupiah(broker_5d['local_net'])}", new_x='LMARGIN', new_y='NEXT')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    if broker_5d['foreign_buyers']:
        pdf.body_text("Top Buyer Asing:")
        buyer_table = [[b['broker'] + ' (F)', format_rupiah(b['net_value'])]
                       for b in broker_5d['foreign_buyers'][:3]]
        pdf.add_table(["Broker", "Net Buy"], buyer_table, [60, 130])

    if broker_5d['local_buyers']:
        pdf.body_text("Top Buyer Lokal:")
        buyer_table = [[b['broker'] + ' (L)', format_rupiah(b['net_value'])]
                       for b in broker_5d['local_buyers'][:3]]
        pdf.add_table(["Broker", "Net Buy"], buyer_table, [60, 130])

    pdf.section_title("C. Statistik Broker (5 Hari)")
    pdf.key_value("Hari Net Buy > Net Sell", f"{flow_stats_5d['accum_days']}/{flow_stats_5d['total_days']} hari")
    pdf.key_value("Hari Net Sell > Net Buy", f"{flow_stats_5d['dist_days']}/{flow_stats_5d['total_days']} hari")
    pdf.key_value("Total Net Flow", format_rupiah(flow_stats_5d['total_net']))

    # ════════════════════════════════════════════════════════════
    # ANALISA 2: PERIODE OPTIMAL (12 Hari Trading)
    # ════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.chapter_title(2, f"ANALISA OPTIMAL ({OPTIMAL_DAYS} Hari Trading)")

    pdf.section_title("A. Broker Flow (12 Hari)")
    pdf.key_value("Total Net Flow", format_rupiah(broker_12d['total_net']))

    # Foreign vs Local breakdown
    pdf.ln(2)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(0, 100, 200)
    pdf.cell(95, 6, f"ASING: {format_rupiah(broker_12d['foreign_net'])}")
    pdf.set_text_color(100, 100, 100)
    pdf.cell(95, 6, f"LOKAL: {format_rupiah(broker_12d['local_net'])}", new_x='LMARGIN', new_y='NEXT')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    if broker_12d['foreign_buyers']:
        pdf.body_text("Top Buyer Asing:")
        buyer_table = [[b['broker'] + ' (F)', format_rupiah(b['net_value'])]
                       for b in broker_12d['foreign_buyers'][:5]]
        pdf.add_table(["Broker", "Net Buy"], buyer_table, [60, 130])

    if broker_12d['local_buyers']:
        pdf.body_text("Top Buyer Lokal:")
        buyer_table = [[b['broker'] + ' (L)', format_rupiah(b['net_value'])]
                       for b in broker_12d['local_buyers'][:5]]
        pdf.add_table(["Broker", "Net Buy"], buyer_table, [60, 130])

    pdf.section_title("B. Statistik Broker (12 Hari)")
    pdf.key_value("Hari Net Buy > Net Sell", f"{flow_stats_12d['accum_days']}/{flow_stats_12d['total_days']} hari")
    pdf.key_value("Hari Net Sell > Net Buy", f"{flow_stats_12d['dist_days']}/{flow_stats_12d['total_days']} hari")
    pdf.key_value("Total Net Flow", format_rupiah(flow_stats_12d['total_net']))

    pdf.section_title("C. Sinyal Akumulasi (dari localhost)")
    pdf.key_value("Sinyal", accum_main['signal'], accum_main.get('color'))
    pdf.key_value("CPR", f"{accum_main['cpr_pct']}%")
    pdf.key_value("CPR Signal", accum_main['cpr_signal'])
    pdf.ln(2)

    # Penjelasan CPR
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(80, 80, 80)
    cpr_explanation = f"""CPR (Close Position Ratio) = posisi close relatif terhadap range harian.
CPR 0-30% = Close dekat LOW (Distribusi/penjual dominan)
CPR 30-70% = Close di tengah (Netral)
CPR 70-100% = Close dekat HIGH (Akumulasi/pembeli dominan)
CDIA CPR {accum_main['cpr_pct']}% = Close dekat LOW = {accum_main['cpr_signal']}"""
    pdf.multi_cell(0, 5, cpr_explanation)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Komponen Validasi
    pdf.set_font('Helvetica', 'B', 10)
    pdf.body_text("Komponen Validasi (7 indikator):")

    accum_count = 0
    dist_count = 0
    neutral_count = 0
    components = accum_main.get('components', {})

    comp_table = []
    for comp, sig in components.items():
        comp_table.append([comp.upper(), sig])
        if 'AKUMULASI' in str(sig).upper():
            accum_count += 1
        elif 'DISTRIBUSI' in str(sig).upper():
            dist_count += 1
        else:
            neutral_count += 1

    if comp_table:
        pdf.add_table(["Komponen", "Sinyal"], comp_table, [90, 100])

    # Penjelasan kenapa NETRAL
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.body_text(f"Summary: {accum_count} Akumulasi, {dist_count} Distribusi, {neutral_count} Lainnya")

    if accum_main['signal'] == 'NETRAL':
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(200, 150, 0)
        pdf.multi_cell(0, 5, "Sinyal NETRAL karena komponen MIXED (ada yang akumulasi, ada yang distribusi). Tunggu konfirmasi lebih jelas sebelum entry.")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    pdf.section_title("D. Support & Resistance")
    if supports:
        pdf.key_value("Support", f"Rp {supports[0]['level']:,.0f} (Strength: {supports[0]['strength']})")
    if resistances:
        pdf.key_value("Resistance", f"Rp {resistances[0]['level']:,.0f}")

    entry_zone = decision.get('entry_zone', {})
    if entry_zone:
        pdf.key_value("Zona Entry", f"Rp {entry_zone.get('low', 0):,.0f} - Rp {entry_zone.get('high', 0):,.0f}")
    pdf.key_value("Invalidation", f"Rp {decision.get('invalidation_price', 0):,.0f}")

    pdf.section_title("E. Fundamental")
    per = fundamental.get('per', 0)
    pbv = fundamental.get('pbvr', 0)
    roe = fundamental.get('roe', 0) * 100

    # Valuasi assessment
    if per > 50 or pbv > 5:
        valuasi = "MAHAL"
        val_color = (200, 0, 0)
    elif per < 15 and pbv < 2:
        valuasi = "MURAH"
        val_color = (0, 150, 0)
    else:
        valuasi = "WAJAR"
        val_color = (0, 100, 200)

    pdf.key_value("PER", f"{per:.2f}x")
    pdf.key_value("PBV", f"{pbv:.2f}x")
    pdf.key_value("ROE", f"{roe:.2f}%")
    pdf.key_value("Valuasi", valuasi, val_color)

    # ════════════════════════════════════════════════════════════
    # KESIMPULAN
    # ════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.chapter_title(3, "KESIMPULAN")

    pdf.section_title("A. Ringkasan Sinyal")

    # Calculate ratio for display
    ratio_5d = (flow_stats_5d['accum_days'] / flow_stats_5d['total_days'] * 100) if flow_stats_5d['total_days'] > 0 else 0
    ratio_12d = (flow_stats_12d['accum_days'] / flow_stats_12d['total_days'] * 100) if flow_stats_12d['total_days'] > 0 else 0

    summary_table = [
        ["Periode", "Hari Akum", "Net Flow"],
        [f"{SHORT_TERM_DAYS} Hari", f"{flow_stats_5d['accum_days']}/{flow_stats_5d['total_days']}", format_rupiah(broker_5d['total_net'])],
        [f"{OPTIMAL_DAYS} Hari", f"{flow_stats_12d['accum_days']}/{flow_stats_12d['total_days']}", format_rupiah(broker_12d['total_net'])],
    ]
    pdf.add_table(summary_table[0], summary_table[1:], [50, 70, 70])

    pdf.key_value("Sinyal Utama (Localhost)", accum_main['signal'], accum_main.get('color'))
    pdf.ln(3)

    pdf.section_title("B. Interpretasi")

    # Logic berdasarkan sinyal dari localhost
    main_signal = accum_main['signal']
    if 'AKUMULASI' in main_signal:
        interp = "BULLISH - Terdeteksi pola akumulasi. Institusi sedang mengumpulkan saham."
        interp_color = (0, 150, 0)
    elif 'DISTRIBUSI' in main_signal:
        interp = "BEARISH - Terdeteksi pola distribusi. Institusi sedang menjual."
        interp_color = (200, 0, 0)
    else:
        interp = "NETRAL - Sinyal belum jelas (mixed). Tunggu konfirmasi sebelum entry."
        interp_color = (100, 100, 100)

    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(*interp_color)
    pdf.multi_cell(0, 7, interp)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    pdf.section_title("C. Rekomendasi")

    rekomendasi = f"""
Keputusan: {main_decision}
Posisi: {position}

"""
    if main_decision == 'BUY' or position == 'IN_ZONE':
        if supports:
            rekomendasi += f"""Entry Zone: Rp {entry_zone.get('low', 0):,.0f} - Rp {entry_zone.get('high', 0):,.0f}
Stop Loss: Rp {decision.get('invalidation_price', 0):,.0f}
Support: Rp {supports[0]['level']:,.0f}
"""
        if resistances:
            rekomendasi += f"Target: Rp {resistances[0]['level']:,.0f}\n"
    else:
        rekomendasi += """Saat ini belum ada sinyal entry yang jelas.
Tunggu konfirmasi akumulasi atau breakout resistance.
"""

    pdf.body_text(rekomendasi)

    pdf.section_title("D. Risiko")
    risks = []
    if per > 50:
        risks.append(f"PER {per:.1f}x sangat tinggi (valuasi mahal)")
    if pbv > 5:
        risks.append(f"PBV {pbv:.1f}x di atas rata-rata")
    if 'DISTRIBUSI' in accum_main['signal']:
        risks.append("Pola distribusi terdeteksi")
    if accum_main['cpr_signal'] == 'DISTRIBUSI':
        risks.append(f"CPR {accum_main['cpr_pct']}% menunjukkan tekanan jual")
    if main_decision == 'WAIT':
        risks.append("Sinyal belum jelas, timing entry belum optimal")

    if risks:
        for r in risks:
            pdf.body_text(f"* {r}")
    else:
        pdf.body_text("Tidak ada risiko signifikan terdeteksi.")

    # ════════════════════════════════════════════════════════════
    # EDUKASI RINGKAS (DINAMIS - bukan template)
    # ════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.chapter_title(4, "EDUKASI: MEMAHAMI SINYAL")

    # Generate education data
    education = generate_signal_education(validation, accum_main, broker_12d, fundamental)

    # A. Kenapa Status [X]?
    pdf.section_title(f"A. Kenapa Status {accum_main['signal']}?")

    # Box explanation
    pdf.set_fill_color(250, 250, 230)
    pdf.rect(10, pdf.get_y(), 190, 25, 'DF')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(60, 60, 60)
    pdf.set_xy(12, pdf.get_y() + 3)
    pdf.multi_cell(186, 5, education['signal_explanation'])
    pdf.ln(8)
    pdf.set_text_color(0, 0, 0)

    # B. Absorption Box (jika applicable)
    absorption = generate_absorption_explanation(
        accum_main['cpr_pct'],
        broker_12d,
        decision.get('decision', 'WAIT')
    )

    if absorption:
        pdf.section_title(f"B. {absorption['title']}")
        pdf.set_fill_color(255, 248, 220)
        pdf.rect(10, pdf.get_y(), 190, 35, 'DF')
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(100, 80, 0)
        pdf.set_xy(12, pdf.get_y() + 3)
        pdf.multi_cell(186, 5, absorption['explanation'])
        pdf.ln(3)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)

    # C. Kenapa Belum Buy? (jika WAIT)
    if education['why_not_buy']:
        pdf.section_title("C. Kenapa Belum Buy?")
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(180, 0, 0)
        for i, reason in enumerate(education['why_not_buy'], 1):
            pdf.cell(8, 6, f"{i}.")
            pdf.multi_cell(175, 6, reason)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # D. Tunggu Konfirmasi Apa?
    if education['wait_for_confirmation']:
        pdf.section_title("D. Tunggu Konfirmasi Apa?")
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(0, 100, 0)
        for i, conf in enumerate(education['wait_for_confirmation'], 1):
            pdf.cell(8, 6, f"{i}.")
            pdf.multi_cell(175, 6, conf)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # E. Faktor Positif (jika ada)
    if education['positive_factors']:
        pdf.section_title("E. Faktor Positif yang Terdeteksi")
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(0, 120, 0)
        for factor in education['positive_factors']:
            pdf.cell(5, 6, "+")
            pdf.multi_cell(180, 6, factor)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # F. Warning / Risiko Tambahan
    if education['warning_factors']:
        pdf.section_title("F. Peringatan Tambahan")
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(200, 100, 0)
        for warn in education['warning_factors']:
            pdf.cell(5, 6, "!")
            pdf.multi_cell(180, 6, warn)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # G. Catatan Penting
    pdf.section_title("G. Catatan Penting")
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(80, 80, 80)
    catatan = """Sistem ini dirancang untuk MELINDUNGI investor dari entry prematur.
Signal WAIT atau NETRAL BUKAN berarti saham jelek - tapi timing belum tepat.
Lebih baik kehilangan opportunity daripada kehilangan modal.
Tunggu konfirmasi yang jelas sebelum masuk posisi."""
    pdf.multi_cell(0, 5, catatan)
    pdf.set_text_color(0, 0, 0)

    # ════════════════════════════════════════════════════════════
    # INFO TAMBAHAN (tidak ada di menu Analysis)
    # ════════════════════════════════════════════════════════════
    pdf.ln(10)
    pdf.chapter_title(5, "INFO TAMBAHAN")

    pdf.section_title("A. Perbandingan Periode")
    pdf.body_text(f"""Analisis menggunakan 2 periode berbeda:
- {SHORT_TERM_DAYS} hari: Menangkap momentum short-term dan noise
- {OPTIMAL_DAYS} hari: Periode optimal berdasarkan pola historis uptrend

Kenapa {OPTIMAL_DAYS} hari optimal? Berdasarkan analisis pola akumulasi yang berhasil menjadi uptrend, mayoritas sinyal muncul dalam window {OPTIMAL_DAYS} trading days.""")

    pdf.section_title("B. Interpretasi Broker Asing vs Lokal")
    foreign_pct = abs(broker_12d['foreign_net']) / max(abs(broker_12d['total_net']), 1) * 100 if broker_12d['total_net'] != 0 else 0
    pdf.body_text(f"""Kontribusi Asing: {foreign_pct:.1f}% dari total flow

Broker Asing (Foreign): Umumnya institusi besar dengan horizon investasi lebih panjang.
Broker Lokal: Campuran retail dan institusi lokal.

Jika Foreign dominan BUY: Confidence lebih tinggi (smart money)
Jika Foreign dominan SELL: Waspada potential outflow berkelanjutan""")

    pdf.section_title("C. Kapan Entry Ideal?")
    pdf.body_text("""Entry ideal ketika SEMUA kondisi terpenuhi:
1. Signal AKUMULASI (bukan NETRAL/DISTRIBUSI)
2. Decision = BUY atau IN_ZONE
3. CPR > 50% (buyer berhasil push harga)
4. Foreign flow POSITIF
5. Tidak ada resistance kuat di dekat entry

Jika salah satu belum terpenuhi, sistem akan mengatakan WAIT.""")

    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 4, """DISCLAIMER: Analisis ini bersifat edukatif dan bukan rekomendasi investasi.
Keputusan investasi sepenuhnya tanggung jawab investor. Selalu lakukan riset mandiri.""")

    # Save PDF
    today = datetime.now().strftime('%Y%m%d')
    filename = f"{stock_code}_{today}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf.output(filepath)

    print(f"\n{'='*60}")
    print(f"PDF BERHASIL DIBUAT!")
    print(f"{'='*60}")
    print(f"File: {filepath}")
    print(f"Periode: {SHORT_TERM_DAYS} hari + {OPTIMAL_DAYS} hari")
    print(f"{'='*60}")

    return filepath


if __name__ == "__main__":
    stock_code = sys.argv[1] if len(sys.argv) > 1 else "CDIA"
    generate_pdf_report(stock_code.upper())
