"""
Generate PDF Stock Analysis Report
Output: STOCKCODE_YYYYMMDD.pdf
"""
import sys
import os
import json
from datetime import datetime
from fpdf import FPDF

# Add app directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from export_analysis_data import export_all_data

class StockReportPDF(FPDF):
    def __init__(self, stock_code):
        super().__init__()
        self.stock_code = stock_code
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Analisis Saham {self.stock_code} - HermanStock', align='L')
        self.cell(0, 10, datetime.now().strftime('%d %B %Y'), align='R', new_x='LMARGIN', new_y='NEXT')
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Halaman {self.page_no()}/{{nb}} | Generated by Claude AI', align='C')

    def chapter_title(self, num, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_fill_color(41, 128, 185)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, f'  {num}. {title}', fill=True, new_x='LMARGIN', new_y='NEXT')
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(41, 128, 185)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def key_value(self, key, value, highlight=False):
        self.set_font('Helvetica', 'B', 10)
        self.cell(60, 6, key + ":")
        self.set_font('Helvetica', '', 10)
        if highlight:
            self.set_text_color(0, 128, 0) if 'BULL' in str(value).upper() or 'BUY' in str(value).upper() or 'ACCUM' in str(value).upper() else self.set_text_color(200, 0, 0) if 'BEAR' in str(value).upper() or 'SELL' in str(value).upper() or 'DIST' in str(value).upper() else self.set_text_color(0, 0, 0)
        self.cell(0, 6, str(value), new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)

    def add_table(self, headers, data):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(230, 230, 230)
        col_width = 190 / len(headers)
        for h in headers:
            self.cell(col_width, 7, h, border=1, fill=True, align='C')
        self.ln()
        self.set_font('Helvetica', '', 9)
        for row in data:
            for cell in row:
                self.cell(col_width, 6, str(cell)[:20], border=1, align='C')
            self.ln()
        self.ln(3)


def format_rupiah(val):
    if val is None:
        return "N/A"
    if abs(val) >= 1e12:
        return f"Rp {val/1e12:,.2f} T"
    elif abs(val) >= 1e9:
        return f"Rp {val/1e9:,.2f} M"
    else:
        return f"Rp {val:,.0f}"


def generate_pdf_report(stock_code: str, output_dir: str = None):
    """Generate PDF report for stock analysis"""

    if output_dir is None:
        output_dir = r"C:\doc Herman\analisa analysis"

    os.makedirs(output_dir, exist_ok=True)

    print(f"Mengambil data {stock_code}...")
    data = export_all_data(stock_code)

    # Create PDF
    pdf = StockReportPDF(stock_code)
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 15, f'ANALISIS SAHAM {stock_code}', align='C', new_x='LMARGIN', new_y='NEXT')

    profile = data.get('company_profile', {})
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, profile.get('company_name', stock_code), align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(5)

    # Current Price Box
    price = data.get('current_price', 0)
    composite = data.get('composite_score', {})
    action = composite.get('action', 'N/A')
    score = composite.get('composite_score', 0)

    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(200, 200, 200)
    pdf.rect(10, pdf.get_y(), 190, 25, 'DF')
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(95, 12, f'Harga: Rp {price:,.0f}', align='C')

    # Color based on action
    if 'BUY' in action:
        pdf.set_text_color(0, 150, 0)
    elif 'WATCH' in action:
        pdf.set_text_color(200, 150, 0)
    else:
        pdf.set_text_color(200, 0, 0)
    pdf.cell(95, 12, f'Signal: {action} ({score})', align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(15)

    # ═══════════════════════════════════════════════════════════════
    # 1. RINGKASAN EKSEKUTIF
    # ═══════════════════════════════════════════════════════════════
    pdf.chapter_title(1, "RINGKASAN EKSEKUTIF")

    movements = data.get('price_movements', {}).get('periods', {})
    m1m = movements.get('1M', {}).get('change_pct', 0)
    foreign = data.get('foreign_flow', {})
    accum = data.get('accumulation_phase', {})

    summary = f"""Saham {stock_code} saat ini diperdagangkan di harga Rp {price:,.0f} dengan sinyal {action} (skor komposit: {score}).

Pergerakan 1 bulan terakhir: {m1m:.2f}%
Foreign Flow Signal: {foreign.get('signal', 'N/A')} (Score: {foreign.get('score', 0)})
Accumulation Phase: {accum.get('phase', 'N/A')} (Score: {accum.get('score', 0)})

"""

    if foreign.get('signal') == 'STRONG_ACCUMULATION' and m1m < 0:
        summary += "INSIGHT: Terdeteksi pola 'accumulation during weakness' - institusi membeli saat harga turun. Ini bisa jadi tanda bottoming process."
    elif foreign.get('signal') == 'STRONG_ACCUMULATION':
        summary += "INSIGHT: Akumulasi kuat dari institusi asing mendukung potensi kenaikan harga."
    elif 'DISTRIBUTION' in str(foreign.get('signal', '')):
        summary += "INSIGHT: Terdeteksi distribusi oleh institusi. Waspadai potensi koreksi."
    else:
        summary += "INSIGHT: Sinyal masih mixed. Tunggu konfirmasi sebelum mengambil posisi."

    pdf.body_text(summary)

    # ═══════════════════════════════════════════════════════════════
    # 2. ANALISIS TEKNIKAL
    # ═══════════════════════════════════════════════════════════════
    pdf.chapter_title(2, "ANALISIS TEKNIKAL")

    pdf.section_title("A. Pergerakan Harga Multi-Periode")
    price_table = [
        ["1 Hari", f"{movements.get('1D', {}).get('change_pct', 0):.2f}%", movements.get('1D', {}).get('direction', '-')],
        ["1 Minggu", f"{movements.get('1W', {}).get('change_pct', 0):.2f}%", movements.get('1W', {}).get('direction', '-')],
        ["2 Minggu", f"{movements.get('2W', {}).get('change_pct', 0):.2f}%", movements.get('2W', {}).get('direction', '-')],
        ["1 Bulan", f"{movements.get('1M', {}).get('change_pct', 0):.2f}%", movements.get('1M', {}).get('direction', '-')],
    ]
    pdf.add_table(["Periode", "Perubahan", "Arah"], price_table)

    pdf.section_title("B. Support & Resistance")
    sr = data.get('support_resistance', {})
    supports = sr.get('supports', [])
    resistances = sr.get('resistances', [])

    if supports:
        pdf.body_text(f"Support Utama: Rp {supports[0].get('level', 0):,.0f} (Strength: {supports[0].get('strength', 0)})")
    if resistances:
        pdf.body_text(f"Resistance Utama: Rp {resistances[0].get('level', 0):,.0f}")

    pdf.section_title("C. Volume Analysis")
    vol = data.get('volume_analysis', {})
    pdf.key_value("Signal", vol.get('signal', 'N/A'), highlight=True)
    pdf.key_value("Score", vol.get('score', 0))

    # ═══════════════════════════════════════════════════════════════
    # 3. ANALISIS BROKER FLOW (BANDARMOLOGY)
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.chapter_title(3, "ANALISIS BROKER FLOW (BANDARMOLOGY)")

    pdf.section_title("A. Foreign Flow Momentum")
    pdf.key_value("Signal", foreign.get('signal', 'N/A'), highlight=True)
    pdf.key_value("Score", f"{foreign.get('score', 0)}/100")
    pdf.ln(3)

    pdf.section_title("B. Smart Money Indicator")
    sm = data.get('smart_money', {})
    pdf.key_value("Signal", sm.get('signal', 'N/A'), highlight=True)
    pdf.key_value("Score", sm.get('score', 0))
    pdf.ln(3)

    pdf.section_title("C. Accumulation Phase")
    pdf.key_value("Phase", accum.get('phase', 'N/A'), highlight=True)
    pdf.key_value("Score", accum.get('score', 0))
    pdf.ln(3)

    pdf.section_title("D. Top Broker Activity (30 Hari)")
    broker_flow = data.get('broker_flow_30d', {})
    buyers = broker_flow.get('top_buyers', [])[:5]
    if buyers:
        buyer_table = [[b['broker'], format_rupiah(b['net_value'])] for b in buyers]
        pdf.add_table(["Broker", "Net Buy"], buyer_table)

    # ═══════════════════════════════════════════════════════════════
    # 4. ANALISIS FUNDAMENTAL
    # ═══════════════════════════════════════════════════════════════
    pdf.chapter_title(4, "ANALISIS FUNDAMENTAL")

    fund = data.get('fundamental', {})

    pdf.section_title("A. Valuasi")
    pdf.key_value("PER", f"{fund.get('per', 0):.2f}x")
    pdf.key_value("PBV", f"{fund.get('pbvr', 0):.2f}x")
    pdf.key_value("ROE", f"{fund.get('roe', 0)*100:.2f}%")
    pdf.key_value("ROA", f"{fund.get('roa', 0)*100:.2f}%")
    pdf.ln(3)

    pdf.section_title("B. Profitabilitas")
    pdf.key_value("Net Profit Margin", f"{fund.get('npm', 0)*100:.2f}%")
    pdf.key_value("Gross Profit Margin", f"{fund.get('gpm', 0)*100:.2f}%")
    pdf.ln(3)

    pdf.section_title("C. Struktur Modal")
    pdf.key_value("DER (Debt to Equity)", f"{fund.get('der', 0):.2f}x")
    pdf.key_value("Current Ratio", f"{fund.get('current_ratio', 0):.2f}x")

    # ═══════════════════════════════════════════════════════════════
    # 5. LEVEL TRADING
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.chapter_title(5, "LEVEL TRADING")

    support_level = supports[0].get('level', price * 0.95) if supports else price * 0.95
    resist_level = resistances[0].get('level', price * 1.05) if resistances else price * 1.05

    pdf.section_title("A. Zona Entry")
    pdf.body_text(f"Entry Konservatif: Rp {support_level:,.0f} - Rp {support_level*1.02:,.0f}")
    pdf.body_text(f"Entry Breakout: Di atas Rp {resist_level:,.0f} dengan volume tinggi")

    pdf.section_title("B. Stop Loss")
    sl = support_level * 0.97
    pdf.body_text(f"Stop Loss: Rp {sl:,.0f} (-{((price-sl)/price)*100:.1f}% dari harga sekarang)")

    pdf.section_title("C. Target Price")
    tp1 = resist_level
    tp2 = resist_level * 1.05
    tp3 = resist_level * 1.15
    pdf.body_text(f"TP1: Rp {tp1:,.0f} (+{((tp1-price)/price)*100:.1f}%)")
    pdf.body_text(f"TP2: Rp {tp2:,.0f} (+{((tp2-price)/price)*100:.1f}%)")
    pdf.body_text(f"TP3: Rp {tp3:,.0f} (+{((tp3-price)/price)*100:.1f}%)")

    # ═══════════════════════════════════════════════════════════════
    # 6. RISIKO
    # ═══════════════════════════════════════════════════════════════
    pdf.chapter_title(6, "RISIKO & PERINGATAN")

    risks = []
    per = fund.get('per', 0)
    pbv = fund.get('pbvr', 0)

    if per > 50:
        risks.append(f"Valuasi Mahal: PER {per:.1f}x sangat tinggi, rentan koreksi jika ekspektasi tidak tercapai")
    if pbv > 5:
        risks.append(f"PBV Premium: PBV {pbv:.1f}x menunjukkan harga jauh di atas book value")
    if m1m < -10:
        risks.append(f"Downtrend: Harga turun {abs(m1m):.1f}% dalam sebulan, momentum masih negatif")
    if sm.get('signal') == 'WEAK':
        risks.append("Smart Money Lemah: Institusi belum menunjukkan conviction penuh")
    if not composite.get('layer1_filter', {}).get('passed', True):
        risks.append("Layer 1 Filter: Tidak lolos kriteria dasar untuk sinyal BUY kuat")

    if risks:
        for r in risks:
            pdf.body_text(f"* {r}")
            pdf.ln(1)
    else:
        pdf.body_text("Tidak ada risiko signifikan yang terdeteksi.")

    # ═══════════════════════════════════════════════════════════════
    # 7. KESIMPULAN
    # ═══════════════════════════════════════════════════════════════
    pdf.chapter_title(7, "KESIMPULAN & REKOMENDASI")

    conclusion = f"""
SIGNAL: {action}
COMPOSITE SCORE: {score}/100

REKOMENDASI:
"""
    if 'BUY' in action:
        conclusion += f"""
- Entry di zona Rp {support_level:,.0f} - Rp {price:,.0f}
- Stop Loss di Rp {sl:,.0f}
- Target: TP1 Rp {tp1:,.0f}, TP2 Rp {tp2:,.0f}
- Position sizing: Max 5% portfolio
"""
    elif 'WATCH' in action:
        conclusion += f"""
- Tunggu konfirmasi breakout di atas Rp {resist_level:,.0f}
- Atau tunggu test support Rp {support_level:,.0f} berhasil
- Jangan terburu-buru entry, pantau volume
"""
    else:
        conclusion += """
- Hindari entry saat ini
- Tunggu sinyal membaik
- Fokus pada saham lain dengan sinyal lebih baik
"""

    pdf.body_text(conclusion)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 4, """DISCLAIMER: Analisis ini bersifat edukatif dan bukan rekomendasi investasi. Keputusan investasi sepenuhnya tanggung jawab investor. Selalu lakukan riset mandiri. Past performance does not guarantee future results.""")

    # Save PDF
    today = datetime.now().strftime('%Y%m%d')
    filename = f"{stock_code}_{today}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf.output(filepath)

    print(f"\n{'='*60}")
    print(f"PDF BERHASIL DIBUAT!")
    print(f"{'='*60}")
    print(f"File: {filepath}")
    print(f"{'='*60}")

    return filepath


if __name__ == "__main__":
    stock_code = sys.argv[1] if len(sys.argv) > 1 else "BBCA"
    generate_pdf_report(stock_code.upper())
